title: The start of being good at something, is being really bad at it! 
author: NateShell
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
An idiot trying to use GitHub Pages
theme: minima
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
